

const Heroes = () => {
  return (
    <header data-framer-name="Hero Section" name="Hero Section" style={{ placeContent: 'center', alignItems: 'center', background: 'rgba(0, 0, 0, 0) linear-gradient(rgb(253, 242, 236) 0%, rgb(255, 255, 255) 100%) repeat scroll 0% 0% / auto padding-box border-box', display: 'flex', flex: '0 0 auto', flexFlow: 'column nowrap', gap: '0px', height: '1317.6px', overflow: 'hidden', padding: '100px 0px 0px', position: 'relative', width: '100%', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased' }}>
      <div data-framer-name="Container" name="Container" style={{ placeContent: 'center', alignItems: 'center', display: 'flex', flex: '0 0 auto', flexFlow: 'column nowrap', gap: '80px', height: '393.6px', maxWidth: '1200px', overflow: 'hidden', padding: '0px', position: 'relative', width: '90%', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased' }}>
        <div data-framer-name="Content" name="Content" style={{ placeContent: 'center', alignItems: 'center', display: 'flex', flex: '0 0 auto', flexFlow: 'column nowrap', gap: '0px', height: '393.6px', overflow: 'visible', padding: '0px 0px 10px', position: 'relative', width: '100%', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased' }}>
          <div data-framer-name="Heading wrapper" name="Heading wrapper" style={{ opacity: 1, transform: 'matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0.000833333, 0, 0, 0, 1)', placeContent: 'center', alignItems: 'center', display: 'flex', flex: '0 0 auto', flexFlow: 'column nowrap', gap: '8px', height: '237.6px', maxWidth: '1200px', overflow: 'hidden', padding: '0px 0px 30px', position: 'relative', width: '100%', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased' }}>
            <div style={{ flex: '0 0 auto', height: 'auto', position: 'relative', width: 'auto', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased' }}>
              <div style={{ display: 'contentsbox-sizing:border-box', WebkitFontSmoothing: 'antialiased' }} tabIndex="0">
                <div data-border="true" data-framer-name="With Icon" style={{borderBottomWidth: '1px', borderColor: 'rgba(130, 71, 255, 0.2)', borderLeftWidth: '1px', borderRightWidth: '1px', borderStyle: 'solid', borderTopWidth: '1px', backgroundColor: 'rgb(255, 255, 255)', borderRadius: '8px', opacity: 1, placeContent: 'center', alignItems: 'center', display: 'flex', flexFlow: 'row nowrap', gap: '6px', height: '29.6px', padding: '4px 10px', position: 'relative', width: 'min-content', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
                <div style={{ outline: 'none', display: 'flex', flexDirection: 'column', justifyContent: 'flex-start', flexShrink: 0,  extractedR6o4lv: 'var(--token-8d3b0b5c-ed9a-45d2-b302-4c9cef737fdc, rgb(130, 71, 255))', framerLinkTextColor: 'rgb(0, 153, 255)', framerLinkTextDecoration: 'underline', framerParagraphSpacing: '0px', transform: 'none', opacity: 1, position: 'relative', flex: '0 0 auto', height: 'auto', whiteSpace: 'pre', width: 'auto', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}} data-framer-component-type="RichTextContainer">
                <p style={{fontSelector: 'R0Y7T3V0Zml0LTYwMA==', framerFontFamily: '&quot', framerFontSize: '18px', framerFontWeight: 600, framerTextColor: 'var(--extracted-r6o4lv)font-family:Outfit, sans-serif', fontStyle: 'normal', fontWeight: 600, color: 'rgb(130, 71, 255)', fontSize: '18px', letterSpacing: 'normal', textTransform: 'none', textDecoration: 'none solid rgb(130, 71, 255)', lineHeight: '21.6px', textAlign: 'start', margin: '0px', padding: '0px', fontFamily: 'Outfit, sans-serif', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>👋</p>
            </div>
            <div style={{ outline: 'none', display: 'flex', flexDirection: 'column', justifyContent: 'flex-start', flexShrink: 0,  extractedR6o4lv: 'var(--token-8d3b0b5c-ed9a-45d2-b302-4c9cef737fdc, rgb(130, 71, 255))', framerLinkTextColor: 'rgb(0, 153, 255)', framerLinkTextDecoration: 'underline', framerParagraphSpacing: '0px', transform: 'none', opacity: 1, position: 'relative', flex: '0 0 auto', height: 'auto', whiteSpace: 'pre', width: 'auto', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}} data-framer-component-type="RichTextContainer">
            <p style={{fontSelector: 'R0Y7T3V0Zml0LTYwMA==', framerFontFamily: '&quot', framerFontSize: '12px', framerFontWeight: 600, framerLetterSpacing: '0.08em', framerTextColor: 'var(--extracted-r6o4lv)', framerTextTransform: 'uppercasefont-family:Outfit, sans-serif', fontStyle: 'normal', fontWeight: 600, color: 'rgb(130, 71, 255)', fontSize: '12px', letterSpacing: '0.96px', textTransform: 'uppercase', textDecoration: 'none solid rgb(130, 71, 255)', lineHeight: '14.4px', textAlign: 'start', margin: '0px', padding: '0px', fontFamily: 'Outfit, sans-serif', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>Welcome to Manage Wise!</p>
        </div>
      </div>
    </div>
                </div >
  <div data-framer-name="Heading" style={{ outline: 'none', display: 'flex', flexDirection: 'column', justifyContent: 'flex-start', flexShrink: 0, transform: 'noneposition:relative',  framerLinkTextColor: '#0099ff', framerLinkTextDecoration: 'underline', framerParagraphSpacing: '0px', flex: '0 0 auto', height: 'auto', overflow: 'visible', position: 'relative', whiteSpace: 'pre-wrap', width: '100%', wordBreak: 'break-word', overflowWrap: 'break-word', zIndex: 1, boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}} data framer component type="RichTextContainer" >
    <h1 data-styles-preset="UvfdUSADq" style={{framerTextColor: 'var(--token-d23dd5a9-b486-4fa3-8394-2cd7943f28da, rgb(7, 6, 27))font-family:Outfit, sans-serif', fontStyle: 'normal', fontWeight: 500, color: 'rgb(28, 28, 28)', fontSize: '85px', letterSpacing: '-2px', textTransform: 'none', textDecoration: 'none solid rgb(28, 28, 28)', lineHeight: '85px', textAlign: 'center', margin: '0px', padding: '0px', framerFontFamily: '"Outfit", sans-serif', framerFontSize: '85px', framerFontStyle: 'normal', framerFontWeight: 500, framerLetterSpacing: '-2px', framerLineHeight: '1em', framerParagraphSpacing: '40px', framerTextAlignment: 'center', framerTextDecoration: 'none', framerTextTransform: 'none', fontFamily: 'Outfit, sans-serif', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}> Empower your business with
                        {/* */ } <span span style = {{framerTextColor: 'var(--token-64932479-7baa-43ec-9f43-39d03638d132, rgb(254, 129, 98))font-family:Outfit, sans-serif', fontStyle: 'normal', fontWeight: 500, color: 'rgb(254, 129, 98)', fontSize: '85px', letterSpacing: '-2px', textTransform: 'none', textDecoration: 'none solid rgb(254, 129, 98)', lineHeight: '85px', textAlign: 'center', fontFamily: 'Outfit, sans-serif', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased' }}> Strategic</span> insights
{/* */ }
                    </h1 >
                </div >
            </div >
  <div data-framer-name="Paragraph" style={{ outline: 'none', display: 'flex', flexDirection: 'column', justifyContent: 'flex-start', flexShrink: 0, opacity: 1, transform: 'matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0.000833333, 0, 0, 0, 1)', position: 'relative',  framerParagraphSpacing: '0px', flex: '0 0 auto', height: 'auto', maxWidth: '700px', overflow: 'visible', whiteSpace: 'pre-wrap', width: '60%', wordBreak: 'break-word', overflowWrap: 'break-word', zIndex: 3, boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}} data framer component type="RichTextContainer" >
    <p data-styles-preset="zvBqvdKXQ" style={{ fontFamily: 'Inter, sans-serif', fontStyle: 'normal', fontWeight: 500, color: 'rgb(118, 117, 117)', fontSize: '20px', letterSpacing: '-0.5px', textTransform: 'none', textDecoration: 'none solid rgb(118, 117, 117)', lineHeight: '30px', textAlign: 'center', margin: '0px', padding: '0px',  framerFontFamily: '"Inter", sans-serif', framerFontSize: '20px', framerFontStyle: 'normal', framerFontWeight: 500, framerLetterSpacing: '-.5px', framerLineHeight: '1.5em', framerParagraphSpacing: '20px', framerTextAlignment: 'center', framerTextColor: 1, framerTextDecoration: 'none', framerTextTransform: 'none', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}> Powerful management platform designed to streamline your business operations, boost productivity, and drive success</p >
            </div >
  <div data-framer-appear-id="1febxrw" data-framer-name="Buttons wrapper" name="Buttons wrapper" style={{ opacity: 1, transform: 'matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0.000833333, 0, 0, 0, 1)', placeContent: 'center', alignItems: 'center', display: 'flex', flex: '0 0 auto', flexFlow: 'row nowrap', gap: '24px', height: '86px', overflow: 'visible', padding: '30px 0px 0px', position: 'relative', width: 'min-content', zIndex: 1, boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased' }}>
    <div style={{ flex: '0 0 auto', height: '56px', position: 'relative', width: '211px', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased' }}>
      <div style={{ display: 'contentsbox-sizing:border-box', WebkitFontSmoothing: 'antialiased' }} tabIndex="0"><a aria-label="Primary" data-framer-name="Variant 1" data-reset="button" style={{ backgroundColor: 'var(--token-8d3b0b5c-ed9a-45d2-b302-4c9cef737fdc, rgb(130, 71, 255))', borderRadius: '18px', boxShadow: 'none', height: '56px', width: '100%', opacity: 1, borderWidth: '0px', padding: '16px 26px', placeContent: 'center', alignItems: 'center', display: 'flex', flexFlow: 'row nowrap', gap: '8px', position: 'relative', textDecoration: 'none solid rgb(0, 0, 238)', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased' }} tabIndex="0" href="https://templatesunit.lemonsqueezy.com/checkout/buy/181cb12c-ca54-44c6-bebd-46e3b656defc" target="_blank" rel="noopener">
        <div style={{ outline: 'none', display: 'flex', flexDirection: 'column', justifyContent: 'flex-start', flexShrink: 0,  extractedR6o4lv: 'var(--token-20257545-130a-452b-8942-48d79a1f3d66, rgb(255, 255, 255))', framerLinkTextColor: 'rgb(0, 153, 255)', framerLinkTextDecoration: 'underline', framerParagraphSpacing: '0px', transform: 'none', opacity: 1, position: 'relative', flex: '0 0 auto', height: 'auto', whiteSpace: 'pre', width: 'auto', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}} data-framer-component-type="RichTextContainer">
        <p style={{fontSelector: 'R0Y7T3V0Zml0LTYwMA==', framerFontFamily: '&quot', framerFontSize: '20px', framerFontWeight: 600, framerTextColor: 'var(--extracted-r6o4lv)font-family:Outfit, sans-serif', fontStyle: 'normal', fontWeight: 600, color: 'rgb(255, 255, 255)', fontSize: '20px', letterSpacing: 'normal', textTransform: 'none', textDecoration: 'none solid rgb(255, 255, 255)', lineHeight: '24px', textAlign: 'start', margin: '0px', padding: '0px', fontFamily: 'Outfit, sans-serif', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>Get Started</p>
      </div>
    </a></div>
                </div >
                <div style={{flex: '0 0 auto', height: '56px', position: 'relative', width: 'auto', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
                    <div style={{display: 'contentsbox-sizing:border-box', WebkitFontSmoothing: 'antialiased'}} tabIndex="0"><a aria-label="Primary" data-border="true" data-framer-name="Variant 1" data-reset="button" style={{borderBottomWidth: '1px', borderColor: 'rgb(221, 217, 212)', borderLeftWidth: '1px', borderRightWidth: '1px', borderStyle: 'solid', borderTopWidth: '1px', backgroundColor: 'rgb(255, 255, 255)', borderRadius: '18px', height: '56px', opacity: 1, borderWidth: '0px', padding: '16px 26px', placeContent: 'center', alignItems: 'center', display: 'flex', flexFlow: 'row nowrap', gap: '8px', position: 'relative', textDecoration: 'none solid rgb(0, 0, 238)', width: 'min-content', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}} tabIndex="0" href="https://www.youtube.com/" target="_blank" rel="noopener">
                            <div style={{outline: 'none', display: 'flex', flexDirection: 'column', justifyContent: 'flex-start', flexShrink: 0, extractedR6o4lv: 'var(--token-d23dd5a9-b486-4fa3-8394-2cd7943f28da, rgb(7, 6, 27))', framerLinkTextColor: 'rgb(0, 153, 255)', framerLinkTextDecoration: 'underline', framerParagraphSpacing: '0px', transform: 'none', opacity: 1, position: 'relative', flex: '0 0 auto', height: 'auto', whiteSpace: 'pre', width: 'auto', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}} data-framer-component-type="RichTextContainer">
                                <p style={{fontSelector: 'R0Y7T3V0Zml0LTYwMA==', framerFontFamily: '&quot', framerFontSize: '20px', framerFontWeight: 600, framerTextColor: 'var(--extracted-r6o4lv)font-family:Outfit, sans-serif', fontStyle: 'normal', fontWeight: 600, color: 'rgb(28, 28, 28)', fontSize: '20px', letterSpacing: 'normal', textTransform: 'none', textDecoration: 'none solid rgb(28, 28, 28)', lineHeight: '24px', textAlign: 'start', margin: '0px', padding: '0px', fontFamily: 'Outfit, sans-serif', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>Whatch Demo</p>
                            </div>
                            <div style={{opacity: 1, flex: '0 0 auto', height: '24px', position: 'relative', width: '24px', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
                                <div style={{display: 'contentsbox-sizing:border-box', WebkitFontSmoothing: 'antialiased'}}><svg viewBox="0 0 20 20" fill="currentColor" width="24" height="24" color="var(--token-d23dd5a9-b486-4fa3-8394-2cd7943f28da, rgb(7, 6, 27)) /* {&quot;name&quot;:&quot;Dark Blue&quot;} */" style={{width: '100%', height: '24px', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
                                        <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM9.555 7.168A1 1 0 008 8v4a1 1 0 001.555.832l3-2a1 1 0 000-1.664l-3-2z" clip-rule="evenodd" style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}></path>
                                    </svg></div>
                            </div>
                        </a ></div >
                </div >
            </div >
        </div >
    </div >
  <div data-framer-name="Container" name="Container" style={{ placeContent: 'center', alignItems: 'center', display: 'flex', flex: '0 0 auto', flexFlow: 'column nowrap', gap: '10px', height: '824px', overflow: 'hidden', padding: '60px 0px 100px', position: 'relative', width: '90%', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased' }}>
    <div data-framer-name="Hero image" name="Hero image" style={{ opacity: 1, transform: 'matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0.000833333, 0, 0, 0, 1)', placeContent: 'center', alignItems: 'center', borderRadius: '27px', boxShadow: 'rgba(250, 252, 255, 0.08) 0px 0.602187px 0.361312px0.916667px, rgba(250, 252, 255, 0.08) 0px 2.28853px 1.37312px1.83333px, rgba(250, 252, 255, 0.067) 0px 10px 6px2.75px, rgb(227, 231, 237) 0px 34px 30px16px', display: 'flex', flex: '1 0 0px', flexFlow: 'column nowrap', gap: '10px', height: '664px', maxWidth: '1200px', overflow: 'hidden', padding: '0px', position: 'relative', width: '100%', willChange: 'transform', zIndex: 1, boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased' }}>
      <div style={{ position: 'absolute', borderRadius: 'inherit', top: 0, right: 0, bottom: 0, left: '0box-sizing:border-box', WebkitFontSmoothing: 'antialiased' }} data-framer-background-image-wrapper="true"><img src="https://framerusercontent.com/images/t9qCSNfZSNdBCMSiohCGNEIl4.jpg" alt="Graph" srcSet="https://framerusercontent.com/images/t9qCSNfZSNdBCMSiohCGNEIl4.jpg?scale-down-to=512 512w, https://framerusercontent.com/images/t9qCSNfZSNdBCMSiohCGNEIl4.jpg?scale-down-to=1024 1024w, https://framerusercontent.com/images/t9qCSNfZSNdBCMSiohCGNEIl4.jpg?scale-down-to=2048 2048w, https://framerusercontent.com/images/t9qCSNfZSNdBCMSiohCGNEIl4.jpg?scale-down-to=4096 4096w, https://framerusercontent.com/images/t9qCSNfZSNdBCMSiohCGNEIl4.jpg 5768w" sizes="min(90vw, 1200px)" style={{ display: 'block', width: '100%', height: '100%', borderRadius: 'inherit', objectPosition: 'center', objectFit: 'contain', imageRendering: 'autobox-sizing:border-box', WebkitFontSmoothing: 'antialiased' }} /></div>
    </div>
  </div>
</header >
  )
}

export default Heroes